version: "2.1"
services:

  cassandra:
    image: ghcr.io/ezynook/apache-cassandra:4.1.3
    container_name: cassandra
    restart: unless-stopped
    expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumns:
      - cassandra_db:/var/lib/cassandra/data
    networks:
      network:
        ipv4_address: 10.1.2.100

  cassandra-web:
    # image: ghcr.io/ezynook/apache-cassandra-web:4.1.3
    build: ./Web-UI/
    container_name: cassandra-web
    restart: unless-stopped
    depends_on:
    - cassandra
    environment:
      CASSANDRA_HOST_IPS: 10.1.2.100
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
    - 3000:3000
    networks:
      network:
        ipv4_address: 10.1.2.200

volumes:
  cassandra_db: {}

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.2.0/24
          gateway: 10.1.2.1
